=== L2jBrasil/l2ce/dist/version/version.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="version" type="versionType"/>
  <xs:complexType name="fileType">
    <xs:sequence>
      <xs:element type="nodeType" name="node"/>
      <xs:element type="forType" name="for"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="pattern" use="required"/>
  </xs:complexType>
  <xs:complexType name="versionType">
    <xs:sequence>
      <xs:element type="fileType" name="file" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="name"/>
  </xs:complexType>
  <xs:complexType name="forType" mixed="true">
    <xs:choice maxOccurs="unbounded">
      <xs:element type="nodeType" name="node" maxOccurs="unbounded"/>
      <xs:element type="forType" name="for"  maxOccurs="unbounded"//>
    </xs:choice>
    <xs:attribute type="xs:string" name="name" use="required"/>
  </xs:complexType>
  <xs:complexType name="nodeType" mixed="true">
    <xs:sequence>
      <xs:element type="nodeType" name="node"  maxOccurs="unbounded"//>
      <xs:element type="forType" name="for"  maxOccurs="unbounded"//>
    </xs:sequence>
    <xs:attribute type="xs:string" name="name" use="required"/>
    <xs:attribute type="xs:string" name="reader" use="required"/>
    <xs:attribute type="xs:string" name="value" use="optional"/>
  </xs:complexType>
</xs:schema>

=== L2jBrasil/l2ce/dist/version/CT2_HighFive.xml
<?xml version='1.0' encoding='utf-8'?>
<version name="CT2_HighFive" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="version.xsd">
	<file pattern="sysstring-[\w]+\.dat">
		<node name="data" reader="UINT"/>
		<for name="data">
			<node name="id" reader="UINT" />
			<node name="name" reader="ASCF" />
		</for>
		<node name="file_end" reader="ASCF" value="SafePackage" />
	</file>
	<file pattern="systemmsg-[\w]+\.dat">
		<node name="data" reader="UINT"/>
		<for name="data">
			<node name="id" reader="UINT" />
			<node name="UNK_0" reader="UINT" />
			<node name="message" reader="ASCF" />
			<node name="group" reader="UINT" />
			<node name="rgb" reader="UINT" />
			<node name="item_sound" reader="ASCF" />
			<node name="sys_msg_ref" reader="ASCF" />
			<node name="UNK_1_1" reader="UINT" />
			<node name="UNK_1_2" reader="UINT" />
			<node name="UNK_1_3" reader="UINT" />
			<node name="UNK_1_4" reader="UINT" />
			<node name="UNK_1_5" reader="UINT" />
			<node name="sub_msg" reader="ASCF" />
			<node name="type" reader="ASCF" />
		</for>
		<node name="file_end" reader="ASCF" value="SafePackage" />
	</file>
</version>

=== L2jBrasil/l2ce/dist/version/GoD_Orfen.xml
<?xml version='1.0' encoding='utf-8'?>
<version name="GoD_Orfen" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="version.xsd">
	<file pattern="msconditiondata.dat">
		<node name="data" reader="UINT"/>
		<for name="data">
			<node name="skill_id" reader="UINT"/>
			<node name="skill_level" reader="BYTE"/>
			<node name="skill_sublevel" reader="SHORT"/>
			<node name="?" reader="SHORT"/>
			<node name="equiptype" reader="BYTE"/>
			<node name="attack_item_types" reader="BYTE"/>
			<for name="attack_item_types">
				<node name="attack_item_type" reader="BYTE"/>
			</for>
			<node name="stattype" reader="BYTE"/>
			<node name="statpercentage" reader="BYTE"/>
			<node name="up" reader="BYTE"/>
			<node name="hpconsume" reader="SHORT"/>
			<node name="mpconsume1" reader="SHORT"/>
			<node name="mpconsume2" reader="SHORT"/>
			<node name="item_id" reader="UINT"/>
			<node name="itemnum" reader="BYTE"/>

			<node name="ultimateconsumegauge" reader="BYTE"/>

			<node name="caster_buffs" reader="BYTE"/>
			<for name="caster_buffs">
				<node name="buff_id" reader="UINT"/>
				<node name="buff_level" reader="SHORT"/>
				<node name="buff_sublevel" reader="SHORT"/>
			</for>
			<node name="target_buffs" reader="BYTE"/>
			<for name="target_buffs">
				<node name="buff_id" reader="UINT"/>
				<node name="buff_level" reader="SHORT"/>
				<node name="buff_sublevel" reader="SHORT"/>
			</for>
		</for>
		<node name="file_end" reader="ASCF" value="SafePackage"/>
	</file>
</version>

=== L2jBrasil/l2ce/dist/version/CT3_Awakening.xml
<?xml version='1.0' encoding='utf-8'?>
<version name="CT3_Awakening" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="version.xsd">
	<file pattern="flymovename-[\w]+\.dat">
		<node name="data" reader="UINT"/>
		<for name="data">
			<node name="path" reader="UINT" />
			<node name="node" reader="UINT" />
			<node name="name" reader="ASCF" />
		</for>
		<node name="file_end" reader="ASCF" value="SafePackage" />
	</file>
	<file pattern="actionname-[\w]+\.dat">
		<node name="data" reader="UINT"/>
		<for name="data">
			<node name="tag" reader="UINT" />
			<node name="id" reader="UINT" />
			<node name="type" reader="INT" />
			<node name="category" reader="UINT" />
			<node name="category2" reader="SHORT_SHORT" />
			<for name="category2">
				<node name="category2_value" reader="INT" />
			</for>
			<node name="cmd" reader="ASCF" />
			<node name="icon" reader="ASCF" />
			<node name="icon_ex" reader="ASCF" />
			<node name="desc" reader="ASCF" />
			<node name="toggle_group_id" reader="INT" />
			<node name="command" reader="UNICODE" />
		</for>
		<node name="file_end" reader="ASCF" value="SafePackage" />
	</file>
	<file pattern="skillname-[\w]+\.dat">
		<node name="data" reader="UINT"/>
		<for name="data">
			<node name="id" reader="UINT" />
			<node name="level" reader="UINT" />
			<node name="name" reader="ASCF" />
			<node name="description" reader="ASCF" />
			<node name="enchant_power" reader="ASCF" />
			<node name="enchant_description" reader="ASCF" />
		</for>
		<node name="file_end" reader="ASCF" value="SafePackage" />
	</file>
	<file pattern="sysstring-[\w]+\.dat">
		<node name="data" reader="UINT"/>
		<for name="data">
			<node name="id" reader="UINT" />
			<node name="name" reader="ASCF" />
		</for>
		<node name="file_end" reader="ASCF" value="SafePackage" />
	</file>
	<file pattern="questmarkconditiondata.dat">
		<node name="data" reader="UINT"/>
		<for name="data">
			<node name="quest_id" reader="UINT" />
			<node name="npc_id" reader="UINT" />
			<node name="race_filter" reader="SHORT_SHORT" />
			<for name="race_filter">
				<node name="race" reader="UINT" />
			</for>
			<node name="class_filter" reader="SHORT_SHORT" />
			<for name="class_filter">
				<node name="class" reader="UINT" />
			</for>
			<node name="start_npc_x" reader="FLOAT" />
			<node name="start_npc_y" reader="FLOAT" />
			<node name="start_npc_z" reader="FLOAT" />
		</for>
		<node name="file_end" reader="ASCF" value="SafePackage" />
	</file>
	<file pattern="usmmoviedata.dat">
		<node name="data" reader="UINT"/>
		<for name="data">
			<node name="movie_id" reader="UINT" />
			<node name="file_name" reader="ASCF" />
			<node name="pos_x" reader="UINT" />
			<node name="pos_y" reader="UINT" />
			<node name="width" reader="UINT" />
			<node name="height" reader="UINT" />
			<node name="target_anchor_point_type" reader="UINT" />
			<node name="clip_anchor_point_type" reader="UINT" />
			<node name="skin_type" reader="ASCF" />
			<node name="skin_button_type" reader="ASCF" />
		</for>
		<node name="file_end" reader="ASCF" value="SafePackage" />
	</file>
	<file pattern="itemstatdata.dat">
		<node name="data" reader="UINT"/>
		<for name="data">
			<node name="item_id" reader="UINT" />
			<node name="p_def" reader="FLOAT" />
			<node name="m_def" reader="FLOAT" />
			<node name="p_attack" reader="FLOAT" />
			<node name="m_attack" reader="FLOAT" />
			<node name="p_attack_speed" reader="FLOAT" />
			<node name="m_attack_speed" reader="FLOAT" />
			<node name="p_hit" reader="FLOAT" />
			<node name="m_hit" reader="FLOAT" />
			<node name="p_crit" reader="FLOAT" />
			<node name="m_crit" reader="FLOAT" />
			<node name="speed" reader="FLOAT" />
			<node name="shield_defence" reader="FLOAT" />
			<node name="shield_defence_rate" reader="FLOAT" />
			<node name="p_void" reader="FLOAT" />
			<node name="m_void" reader="FLOAT" />
			<node name="property_params" reader="INT" />
		</for>
	</file>
	<file pattern="itemname-[\w]+\.dat">
		<node name="data" reader="UINT"/>
		<for name="data">
			<node name="item_id" reader="UINT" />
			<node name="name" reader="UNICODE" />
			<node name="additionalname" reader="UNICODE" />
			<node name="popup" reader="ASCF" />
			<node name="description" reader="INT" />
			<node name="name_class" reader="UINT" />
			<for name="name_class">
				<node name="name_class_sub" reader="UINT" />
				<for name="name_class_sub">
					<node name="name_class_sub2" reader="UINT" />
				</for>
			</for>
			<node name="setid_1" reader="UINT" />
			<for name="setid_1">
				<node name="seteffect_1" reader="ASCF" />
			</for>
			<node name="setid_2" reader="UINT" />
			<for name="setid_2">
				<node name="seteffect_2_sub" reader="UINT" />
				<for name="seteffect_2_sub">
					<node name="seteffect_2_sub2" reader="UINT" />
				</for>
			</for>
			<node name="setid_3" reader="UINT" />
			<for name="setid_3">
				<node name="seteffect_3" reader="ASCF" />
			</for>
			<node name="unknown_1" reader="UINT" />
			<node name="unknown_2" reader="UINT" />
			<node name="set_enchant_count" reader="UINT" />
			<node name="set_enchant_effect" reader="ASCF" />
			<node name="color" reader="UINT" />
		</for>
		<node name="file_end" reader="ASCF" value="SafePackage" />
	</file>
</version>

=== L2jBrasil/l2ce/dist/version/GoD_Salvation.xml
<?xml version='1.0' encoding='utf-8'?>
<version name="GoD_Salvation" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="version.xsd">
	<file pattern="msconditiondata.dat">
		<node name="data" reader="UINT"/>
		<for name="data">
			<node name="skill_id" reader="UINT"/>
			<node name="skill_level" reader="BYTE"/>
			<node name="skill_sublevel" reader="SHORT"/>
			<node name="equiptype" reader="BYTE"/>
			<node name="attack_item_types" reader="BYTE"/>
			<for name="attack_item_types">
				<node name="attack_item_type" reader="BYTE"/>
			</for>
			<node name="stattype" reader="BYTE"/>
			<node name="statpercentage" reader="BYTE"/>
			<node name="up" reader="BYTE"/>
			<node name="hpconsume" reader="SHORT"/>
			<node name="mpconsume1" reader="SHORT"/>
			<node name="mpconsume2" reader="SHORT"/>
			<node name="item_id" reader="UINT"/>
			<node name="itemnum" reader="BYTE"/>

			<node name="ultimateconsumegauge" reader="BYTE"/>

			<node name="caster_buffs" reader="BYTE"/>
			<for name="caster_buffs">
				<node name="buff_id" reader="UINT"/>
				<node name="buff_level" reader="SHORT"/>
				<node name="buff_sublevel" reader="SHORT"/>
			</for>
			<node name="target_buffs" reader="BYTE"/>
			<for name="target_buffs">
				<node name="buff_id" reader="UINT"/>
				<node name="buff_level" reader="SHORT"/>
				<node name="buff_sublevel" reader="SHORT"/>
			</for>
		</for>
		<node name="file_end" reader="ASCF" value="SafePackage"/>
	</file>

	<file pattern="pawnanimdata.dat">
		<node name="data" reader="UINT"/>
		<for name="data">
			<node name="name_mapid" reader="UINT"/>
			<node name="texture_params" reader="UINT"/>
			<for name="texture_params">
				<node name="index_param" reader="UINT"/>
				<node name="index_num" reader="UINT"/>
				<node name="param_mapid" reader="UINT"/>
			</for>
			<node name="int_params" reader="SHORT_SHORT"/>
			<for name="int_params">
				<node name="index_param1" reader="UINT"/>
				<node name="index_num1" reader="UINT"/>
				<node name="param1" reader="UINT"/>
			</for>
			<node name="int_params2" reader="SHORT_SHORT"/>
			<for name="int_params2">
				<node name="index_param2" reader="UINT"/>
				<node name="index_num2" reader="UINT"/>
				<node name="param2" reader="UINT"/>
			</for>
			<node name="float_params" reader="SHORT_SHORT"/>
			<for name="float_params">
				<node name="index_param3" reader="UINT"/>
				<node name="index_num3" reader="UINT"/>
				<node name="param3" reader="FLOAT"/>
			</for>
		</for>
		<node name="file_end" reader="ASCF" value="SafePackage"/>
	</file>

	<file pattern="skillname-[\w]+\.dat">
		<node name="data" reader="SHORT_SHORT"/>
		<for name="data">
			<node name="name" reader="ASCF"/>
			<node name="index" reader="UINT"/>
		</for>
		<node name="size1" reader="UINT"/>
		<for name="size1">
			<node name="skill_id" reader="UINT"/>
			<node name="skill_level" reader="SHORT"/>
			<node name="skill_sublevel" reader="SHORT"/>
			<node name="prev_skill_id" reader="UINT"/>
			<node name="prev_skill_level" reader="SHORT"/>
			<node name="prev_skill_sublevel" reader="SHORT"/>
			<node name="name" reader="UINT"/>
			<node name="desc" reader="UINT"/>
			<node name="desc_param" reader="UINT"/>
			<node name="enchant_name" reader="UINT"/>
			<node name="enchant_name_param" reader="UINT"/>
			<node name="enchant_desc" reader="UINT"/>
			<node name="enchant_desc_param" reader="UINT"/>
		</for>
	</file>

	<file pattern="l2gamedataname.dat">
		<node name="data" reader="UINT"/>
		<for name="data">
			<node name="name" reader="UNICODE">
				<attribute name="index" expression="$i" />
			</node>
		</for>
		<node name="file_end" reader="ASCF" value="SafePackage"/>
	</file>
</version>
